### PR TITLE
Add support and documentation for R: prefix (JSON curly brackets support)

### PR DESCRIPTION
**Pull request by Elijas**
Solves issue https://github.com/MobileDynasty/pytest-env/issues/11

### CODE REVIEW

**Comment by lgarvey** [comment]
I'm currently struggling with this issue - would be good to see this merged!

**Comment by Elijas** [comment]
> I'm currently struggling with this issue - would be good to see this merged!

You should be able to pip install from my branch. The original devleopers, MobileDynasty seem to have completely abandoned development

**Review by areeb-lululemon — APPROVED** [review]

**Comment by deanq** [comment]
bump

**Comment by Elijas** [comment]
@lgarvey @deanq @areeb-lululemon @lelabo-m The issue is fixed now in the official pytest-env, https://github.com/pytest-dev/pytest-env/pull/9

**Pull request closed without merging**
